### ISSUE TITLE
ash: ./route-override: not found

### ISSUE THREAD

**Issue by maxpain** [redhat-nfvpe/cni-route-override#17]
Hello. I'm trying to use `cni-route-override` with `multus`.
I have a configuration like this:

```yaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cilium
  namespace: kube-system
spec:
  config: |
    {
      "cniVersion": "0.4.0",
      "name": "cilium",
      "plugins": [{
        "type": "cilium-cni",
        "master": "eth1"
      }, {
        "type": "route-override",
        "flushroutes" : true
      }]
    }
```

But when creating a pod with this cni I'm getting this error:
<img width="709" alt="image" src="https://user-images.githubusercontent.com/5875582/186974389-9aa6c276-1360-474f-81a6-8b358363c907.png">

I tried to run `route-override` inside a pod in [`route-override` daemonset](https://github.com/redhat-nfvpe/cni-route-override/blob/master/deployments/daemonset-install.yaml) and got this error:
```sh
./route-override 
ash: ./route-override: not found
```

<img width="609" alt="image" src="https://user-images.githubusercontent.com/5875582/186975417-17487611-a5bd-42ae-a596-80f1b5a524b7.png">
